#!/bin/sh
#
# @Title: {{Title}}
# @Author: {{Author}}
# @Date:  2020-12-12
# @Last Modified by: {{ModifiedBy}}
# @Last Modified time: {{ModifiedTime}}
#
phpPath="$( dirname $(dirname $(cd $(dirname "${BASH_SOURCE[0]}") && pwd) ))/php/base/php.exe"
normphpPath="$( dirname $(dirname $(cd $(dirname "${BASH_SOURCE[0]}") && pwd) ))/helper/public/index_cli.php"
echo $phpPath;
"$phpPath" ${normphpPath}  "--route" /normphp-helper-tool/cli  $@
